networks:
  localNw:
    driver: bridge


services:

  back:
    build:
      context: ./packages/back
      target: dev
      dockerfile: Dockerfile
    container_name: back
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync+restart
          path: ./packages/back/src
          target: /app/src
        - action: sync+restart
          path: ./packages/back/libs
          target: /app/libs
        - action: rebuild
          path: ./packages/back/package.json
        - action: rebuild
          path: ./packages\back\prisma\schema.prisma
    networks:
      - localNw


  front:
    build:
      context: ./packages/front
      target: dev
      dockerfile: Dockerfile
    container_name: front
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - '8080:8080'
    develop:
      watch:
        - action: sync+restart
          path: ./packages/front/src
          target: /app/src
        - action: sync+restart
          path: ./packages/front/public
          target: /app/public
        - action: rebuild
          path: ./packages/front/package.json
        - action: rebuild
          path: ./packages\back\prisma\schema.prisma
    networks:
      - localNw

